apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quota-order-manager.fullname" . }}-config
  namespace: {{ .Values.app.namespace | default .Release.Namespace }}
  labels:
    {{- include "quota-order-manager.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.config.configYaml | nindent 4 }}