# templates/hpa.yaml
{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.appName }}-hpa
  labels:
    app: {{ .Values.appName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.appName }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ (index .Values.hpa.behavior.scaleUp.policies 0).value }}
        periodSeconds: {{ (index .Values.hpa.behavior.scaleUp.policies 0).periodSeconds }}
      - type: Pods
        value: {{ (index .Values.hpa.behavior.scaleUp.policies 1).value }}
        periodSeconds: {{ (index .Values.hpa.behavior.scaleUp.policies 1).periodSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleUp.selectPolicy }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
      - type: Percent
        value: {{ (index .Values.hpa.behavior.scaleDown.policies 0).value }}
        periodSeconds: {{ (index .Values.hpa.behavior.scaleDown.policies 0).periodSeconds }}
      - type: Pods
        value: {{ (index .Values.hpa.behavior.scaleDown.policies 1).value }}
        periodSeconds: {{ (index .Values.hpa.behavior.scaleDown.policies 1).periodSeconds }}
      selectPolicy: {{ .Values.hpa.behavior.scaleDown.selectPolicy }}
{{- end }}