database:
  # 已经在数据库中创建数据库
  databaseName: casdoor
  driver: postgres
  host: "postgresql-ha-pgpool"
  password: costrict
  port: "5432"
  sslMode: disable
  user: costrict


config: |
  appname = casdoor
  httpport = {{ .Values.service.port }}
  runmode = prod
  SessionOn = true
  copyrequestbody = true
  driverName = {{ .Values.database.driver }}
  dataSourceName = {{ include "casdoor.dataSourceName" . }}
  dbName = {{ include "casdoor.dbName" . }}
  redisEndpoint =
  defaultStorageProvider =
  isCloudIntranet = false
  authState = "casdoor"
  socks5Proxy = ""
  verificationCodeTimeout = 10
  initScore = 0
  logPostOnly = true
  origin =
  enableGzip = true
  ldapServerPort = 10389

image:
  name: casdoor
  pullPolicy: IfNotPresent
  repository: "zgsm"
  tag: v2.0.6
