# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}   # 滚动更新时最多允许的不可用容器数
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}               # 滚动更新时最多允许的额外容器数
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        # loki-log-enabled: {{ .Values.lokiLogEnabled | default "true" | quote }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}  # 容器终止宽限期
      containers:
        - name: {{ .Values.containerName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: config
              mountPath: /app/etc/chat-api.yaml
              subPath: chat-api.yaml
            - name: config
              mountPath: /app/etc/rules.yaml      # 新增：挂载 rule.yaml
              subPath: rules.yaml
            - name: pvc-storage
              mountPath: {{ .Values.persistence.mountPath }}
          args: ["-f", "/app/etc/chat-api.yaml"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Values.appName }}-config
            items:
              - key: chat-api.yaml
                path: chat-api.yaml
              - key: rules.yaml
                path: rules.yaml
        - name: pvc-storage
          persistentVolumeClaim:
            claimName: {{ .Values.appName }}-storage